# .github/workflows/jmeter.yml

name: Run JMeter tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Download and extract JMeter
      run: |
        curl -O https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz

    - name: Run JMeter test
      run: |
        apache-jmeter-5.6.3/bin/jmeter -n -t tests/test_plan.jmx -l results/results.jtl

    - name: Upload results as artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: jmeter-results
        path: results/results.jtl
