name: Run JMeter tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download and extract JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Create results and report directories
        run: |
          mkdir -p results
          mkdir -p report

      - name: Run JMeter test
        run: |
          apache-jmeter-5.6.3/bin/jmeter -n -t "tests/case_management_v2.jmx" -l results/results.jtl -j results/jmeter.log

      - name: Generate HTML report
        run: |
          apache-jmeter-5.6.3/bin/jmeter -g results/results.jtl -o report
      
      - name: Vérifier si le fichier JTL existe
        run: |
          ls -al results


      - name: Upload JTL results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: jmeter-jtl-results
          path: results/results.jtl

      - name: Upload HTML report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: jmeter-html-report
          path: report
